In [27]:
import pandas as pd
from google.colab import drive
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.under_sampling import RandomUnderSampler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score, log_loss
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [2]:
drive.mount('/content/gdrive')
data = pd.read_csv('gdrive/My Drive/Datasetjadid.csv')

Mounted at /content/gdrive


In [3]:
data


Id   Income  Age  Experience Married/Single House_Ownership  \
0            1  1303834   23           3         single          rented   
1            2  7574516   40          10         single          rented   
2            3  3991815   66           4        married          rented   
3            4  6256451   41           2         single          rented   
4            5  5768871   47          11         single          rented   
...        ...      ...  ...         ...            ...             ...   
251995  251996  8154883   43          13         single          rented   
251996  251997  2843572   26          10         single          rented   
251997  251998  4522448   46           7         single          rented   
251998  251999  6507128   45           0         single          rented   
251999  252000  9070230   70          17         single          rented   

       Car_Ownership           Profession                 CITY  \
0                 no  Mechanical_engineer                 Rewa   
1                 no   Software_Developer             Parbhani   
2                 no     Technical_writer            Alappuzha   
3                yes   Software_Developer          Bhubaneswar   
4                 no        Civil_servant  Tiruchirappalli[10]   
...              ...                  ...                  ...   
251995            no              Surgeon              Kolkata   
251996            no         Army_officer                 Rewa   
251997            no      Design_Engineer      Kalyan-Dombivli   
251998            no     Graphic_Designer          Pondicherry   
251999            no         Statistician                Avadi   

                 STATE  CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  Risk_Flag  
0       Madhya_Pradesh                3                 13          0  
1          Maharashtra                9                 13          0  
2               Kerala                4                 10          0  
3               Odisha                2                 12          1  
4           Tamil_Nadu                3                 14          1  
...                ...              ...                ...        ...  
251995     West_Bengal                6                 11          0  
251996  Madhya_Pradesh                6                 11          0  
251997     Maharashtra                7                 12          0  
251998      Puducherry                0                 10          0  
251999      Tamil_Nadu                7                 11          0  

[252000 rows x 13 columns]

In [4]:
if data.duplicated().any():
    print(data.duplicated().sum(),"has duplicate data.")
else:
    print("no duplicate.")

no duplicate.


In [5]:
X = data.drop(['Risk_Flag','CITY','STATE'],axis=1)
y = data['Risk_Flag']

In [6]:
X = pd.get_dummies(X,drop_first=True)

In [36]:
X

Id   Income  Age  Experience  CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  \
0            1  1303834   23           3                3                 13   
1            2  7574516   40          10                9                 13   
2            3  3991815   66           4                4                 10   
3            4  6256451   41           2                2                 12   
4            5  5768871   47          11                3                 14   
...        ...      ...  ...         ...              ...                ...   
251995  251996  8154883   43          13                6                 11   
251996  251997  2843572   26          10                6                 11   
251997  251998  4522448   46           7                7                 12   
251998  251999  6507128   45           0                0                 10   
251999  252000  9070230   70          17                7                 11   

        Married/Single_single  House_Ownership_owned  House_Ownership_rented  \
0                           1                      0                       1   
1                           1                      0                       1   
2                           0                      0                       1   
3                           1                      0                       1   
4                           1                      0                       1   
...                       ...                    ...                     ...   
251995                      1                      0                       1   
251996                      1                      0                       1   
251997                      1                      0                       1   
251998                      1                      0                       1   
251999                      1                      0                       1   

        Car_Ownership_yes  ...  Profession_Scientist  Profession_Secretary  \
0                       0  ...                     0                     0   
1                       0  ...                     0                     0   
2                       0  ...                     0                     0   
3                       1  ...                     0                     0   
4                       0  ...                     0                     0   
...                   ...  ...                   ...                   ...   
251995                  0  ...                     0                     0   
251996                  0  ...                     0                     0   
251997                  0  ...                     0                     0   
251998                  0  ...                     0                     0   
251999                  0  ...                     0                     0   

        Profession_Software_Developer  Profession_Statistician  \
0                                   0                        0   
1                                   1                        0   
2                                   0                        0   
3                                   1                        0   
4                                   0                        0   
...                               ...                      ...   
251995                              0                        0   
251996                              0                        0   
251997                              0                        0   
251998                              0                        0   
251999                              0                        1   

        Profession_Surgeon  Profession_Surveyor  Profession_Technical_writer  \
0                        0                    0                            0   
1                        0                    0                            0   
2                        0                    0                            1   
3                        0              

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [10]:
X_train.isnull().sum()

Id                                       0
Income                                   0
Age                                      0
Experience                               0
CURRENT_JOB_YRS                          0
CURRENT_HOUSE_YRS                        0
Married/Single_single                    0
House_Ownership_owned                    0
House_Ownership_rented                   0
Car_Ownership_yes                        0
Profession_Analyst                       0
Profession_Architect                     0
Profession_Army_officer                  0
Profession_Artist                        0
Profession_Aviator                       0
Profession_Biomedical_Engineer           0
Profession_Chartered_Accountant          0
Profession_Chef                          0
Profession_Chemical_engineer             0
Profession_Civil_engineer                0
Profession_Civil_servant                 0
Profession_Comedian                      0
Profession_Computer_hardware_engineer    0
Profession_

In [11]:
X_test.isnull().sum()

Id                                       0
Income                                   0
Age                                      0
Experience                               0
CURRENT_JOB_YRS                          0
CURRENT_HOUSE_YRS                        0
Married/Single_single                    0
House_Ownership_owned                    0
House_Ownership_rented                   0
Car_Ownership_yes                        0
Profession_Analyst                       0
Profession_Architect                     0
Profession_Army_officer                  0
Profession_Artist                        0
Profession_Aviator                       0
Profession_Biomedical_Engineer           0
Profession_Chartered_Accountant          0
Profession_Chef                          0
Profession_Chemical_engineer             0
Profession_Civil_engineer                0
Profession_Civil_servant                 0
Profession_Comedian                      0
Profession_Computer_hardware_engineer    0
Profession_

In [13]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X_train_scaled, y_train)

In [31]:
dt_gini = DecisionTreeClassifier(criterion='gini', random_state=42)
dt_gini.fit(X_resampled, y_resampled)
y_pred_gini = dt_gini.predict(X_test_scaled)
y_pred_proba_gini = dt_gini.predict_proba(X_test_scaled)
print("\n'gini':")
cm_gini = confusion_matrix(y_test, y_pred_gini)
print(f"Confusion Matrix:\n{cm_gini}")
precision_gini = precision_score(y_test, y_pred_gini)
recall_gini = recall_score(y_test, y_pred_gini)
f1_gini = f1_score(y_test, y_pred_gini)
print(f"Precision: {precision_gini:.4f}")
print(f"Recall: {recall_gini:.4f}")
print(f"F1 Score: {f1_gini:.4f}")
accuracy_gini = accuracy_score(y_test, y_pred_gini)
print(f"Accuracy: {accuracy_gini:.4f}")
logloss_gini = log_loss(y_test, y_pred_proba_gini)
print(f"Log Loss: {logloss_gini:.4f}\n")


'gini':
Confusion Matrix:
[[37503 17721]
 [ 2120  5656]]
Precision: 0.2419
Recall: 0.7274
F1 Score: 0.3631
Accuracy: 0.6851
Log Loss: 11.3515



In [32]:
dt_entropy = DecisionTreeClassifier(criterion='entropy', random_state=42)
dt_entropy.fit(X_resampled, y_resampled)
y_pred_entropy = dt_entropy.predict(X_test_scaled)
y_pred_proba_entropy = dt_entropy.predict_proba(X_test_scaled)
print("\n'entropy':")
cm_entropy = confusion_matrix(y_test, y_pred_entropy)
print(f"Confusion Matrix:\n{cm_entropy}")
precision_entropy = precision_score(y_test, y_pred_entropy)
recall_entropy = recall_score(y_test, y_pred_entropy)
f1_entropy = f1_score(y_test, y_pred_entropy)
print(f"Precision: {precision_entropy:.4f}")
print(f"Recall: {recall_entropy:.4f}")
print(f"F1 Score: {f1_entropy:.4f}")
accuracy_entropy = accuracy_score(y_test, y_pred_entropy)
print(f"Accuracy: {accuracy_entropy:.4f}")
logloss_entropy = log_loss(y_test, y_pred_proba_entropy)
print(f"Log Loss: {logloss_entropy:.4f}\n")


'entropy':
Confusion Matrix:
[[38038 17186]
 [ 2104  5672]]
Precision: 0.2481
Recall: 0.7294
F1 Score: 0.3703
Accuracy: 0.6938
Log Loss: 11.0362



In [33]:
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [ None, 5, 10, 15, 20, 25,30]
}
dt = DecisionTreeClassifier(random_state=42)
grid_search = GridSearchCV(dt, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
y_pred_proba = best_model.predict_proba(X_test)
print("\nbestDecision Tree :")
cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{cm}")
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
logloss = log_loss(y_test, y_pred_proba)
print(f"Log Loss: {logloss:.4f}")
print("\nBest Hyperparameters:", best_params)


bestDecision Tree :
Confusion Matrix:
[[55222     2]
 [ 7775     1]]
Precision: 0.3333
Recall: 0.0001
F1 Score: 0.0003
Accuracy: 0.8766
Log Loss: 0.3538

Best Hyperparameters: {'criterion': 'entropy', 'max_depth': 5}


In [22]:
class_0_weight = 1 / (len(y_resampled[y_resampled == 0]) / len(y_resampled))
class_1_weight = 1 / (len(y_resampled[y_resampled == 1]) / len(y_resampled))
linear_svc = LinearSVC(class_weight={0: class_0_weight, 1: class_1_weight}, random_state=42)
linear_svc.fit(X_resampled, y_resampled)
y_pred_linear = linear_svc.predict(X_test_scaled)
confusion_linear = confusion_matrix(y_test, y_pred_linear)
report_linear = classification_report(y_test, y_pred_linear, target_names=['No Risk', 'Risk'])
print("Kernel: Linear\n")
print("Confusion Matrix:\n", confusion_linear)
print("\nClassification Report:\n", report_linear)
print("\n-------------------------------------------\n")

Kernel: Linear

Confusion Matrix:
 [[29680 25544]
 [ 3456  4320]]

Classification Report:
               precision    recall  f1-score   support

     No Risk       0.90      0.54      0.67     55224
        Risk       0.14      0.56      0.23      7776

    accuracy                           0.54     63000
   macro avg       0.52      0.55      0.45     63000
weighted avg       0.80      0.54      0.62     63000


-------------------------------------------



/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [24]:
svc_rbf = SVC(kernel='rbf', class_weight={0: 1/len(y_resampled[y_resampled == 0]), 1: 1/len(y_resampled[y_resampled == 1])}, random_state=42)
svc_rbf.fit(X_resampled, y_resampled)
y_pred_rbf = svc_rbf.predict(X_test_scaled)
confusion_rbf = confusion_matrix(y_test, y_pred_rbf)
report_rbf = classification_report(y_test, y_pred_rbf, target_names=['No Risk', 'Risk'])
print("Kernel: RBF\n")
print("Confusion Matrix:\n", confusion_rbf)
print("\nClassification Report:\n", report_rbf)
print("\n-------------------------------------------\n")

Kernel: RBF

Confusion Matrix:
 [[35045 20179]
 [ 4140  3636]]

Classification Report:
               precision    recall  f1-score   support

     No Risk       0.89      0.63      0.74     55224
        Risk       0.15      0.47      0.23      7776

    accuracy                           0.61     63000
   macro avg       0.52      0.55      0.49     63000
weighted avg       0.80      0.61      0.68     63000


-------------------------------------------



In [25]:
svc_sigmoid = SVC(kernel='sigmoid', class_weight={0: 1/len(y_resampled[y_resampled == 0]), 1: 1/len(y_resampled[y_resampled == 1])}, random_state=42)
svc_sigmoid.fit(X_resampled, y_resampled)
y_pred_sigmoid = svc_sigmoid.predict(X_test_scaled)
confusion_sigmoid = confusion_matrix(y_test, y_pred_sigmoid)
report_sigmoid = classification_report(y_test, y_pred_sigmoid, target_names=['No Risk', 'Risk'])
print("Kernel: Sigmoid\n")
print("Confusion Matrix:\n", confusion_sigmoid)
print("\nClassification Report:\n", report_sigmoid)
print("\n-------------------------------------------\n")

Kernel: Sigmoid

Confusion Matrix:
 [[10560 44664]
 [ 1007  6769]]

Classification Report:
               precision    recall  f1-score   support

     No Risk       0.91      0.19      0.32     55224
        Risk       0.13      0.87      0.23      7776

    accuracy                           0.28     63000
   macro avg       0.52      0.53      0.27     63000
weighted avg       0.82      0.28      0.31     63000


-------------------------------------------



In [26]:
svc_poly = SVC(kernel='poly', class_weight={0: 1/len(y_resampled[y_resampled == 0]), 1: 1/len(y_resampled[y_resampled == 1])}, random_state=42)
svc_poly.fit(X_resampled, y_resampled)
y_pred_poly = svc_poly.predict(X_test_scaled)
confusion_poly = confusion_matrix(y_test, y_pred_poly)
report_poly = classification_report(y_test, y_pred_poly, target_names=['No Risk', 'Risk'])
print("Kernel: Polynomial\n")
print("Confusion Matrix:\n", confusion_poly)
print("\nClassification Report:\n", report_poly)
print("\n-------------------------------------------\n")

Kernel: Polynomial

Confusion Matrix:
 [[25131 30093]
 [ 2671  5105]]

Classification Report:
               precision    recall  f1-score   support

     No Risk       0.90      0.46      0.61     55224
        Risk       0.15      0.66      0.24      7776

    accuracy                           0.48     63000
   macro avg       0.52      0.56      0.42     63000
weighted avg       0.81      0.48      0.56     63000


-------------------------------------------



In [28]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]}
linear_svc = LinearSVC(class_weight={0: 1/len(y_resampled[y_resampled == 0]), 1: 1/len(y_resampled[y_resampled == 1])}, random_state=42)
grid_search = GridSearchCV(linear_svc, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_resampled, y_resampled)
best_C = grid_search.best_params_['C']

In [29]:
final_linear_svc = LinearSVC(C=best_C, class_weight={0: 1/len(y_resampled[y_resampled == 0]), 1: 1/len(y_resampled[y_resampled == 1])}, random_state=42)
final_linear_svc.fit(X_resampled, y_resampled)
y_pred_linear_svc = final_linear_svc.predict(X_test_scaled)
report_linear_svc = classification_report(y_test, y_pred_linear_svc, target_names=['No Risk', 'Risk'])
print(f"Best C: {best_C}\n")
print("Classification Report:\n", report_linear_svc)

Best C: 10

Classification Report:
               precision    recall  f1-score   support

     No Risk       0.90      0.53      0.67     55224
        Risk       0.14      0.56      0.23      7776

    accuracy                           0.54     63000
   macro avg       0.52      0.55      0.45     63000
weighted avg       0.80      0.54      0.61     63000



In [34]:
dt_model = DecisionTreeClassifier(criterion='gini', random_state=42)
dt_model.fit(X_resampled, y_resampled)
y_pred_dt = dt_model.predict(X_test_scaled)
linear_svm_model = LinearSVC(class_weight={0: 1/len(y_resampled[y_resampled == 0]), 1: 1/len(y_resampled[y_resampled == 1])}, random_state=42)
linear_svm_model.fit(X_resampled, y_resampled)
y_pred_linear_svm = linear_svm_model.predict(X_test_scaled)
results_df = pd.DataFrame({'Actual': y_test, 'LinearSVC_Predicted': y_pred_linear_svm, 'DT_Predicted': y_pred_dt})
linear_svm_wrong_dt_right = results_df[(results_df['LinearSVC_Predicted'] != results_df['Actual']) & (results_df['DT_Predicted'] == results_df['Actual'])].head(10)
linear_svm_right_dt_wrong = results_df[(results_df['LinearSVC_Predicted'] == results_df['Actual']) & (results_df['DT_Predicted'] != results_df['Actual'])].head(10)
linear_svm_wrong_dt_wrong = results_df[(results_df['LinearSVC_Predicted'] != results_df['Actual']) & (results_df['DT_Predicted'] != results_df['Actual'])].head(10)
linear_svm_right_dt_right = results_df[(results_df['LinearSVC_Predicted'] == results_df['Actual']) & (results_df['DT_Predicted'] == results_df['Actual'])].head(10)
print("LinearSVC=wrong,Decision Tree = right:\n", linear_svm_wrong_dt_right)
print("\nLinearSVC=right, Decision Tree= wrong:\n", linear_svm_right_dt_wrong)
print("\n LinearSVC = wrong, Decision Tree = wrong:\n", linear_svm_wrong_dt_wrong)
print("\nLinearSVC = right, Decision Tree =right:\n", linear_svm_right_dt_right)


LinearSVC=wrong,Decision Tree = right:
         Actual  LinearSVC_Predicted  DT_Predicted
187455       0                    1             0
135104       0                    1             0
167774       0                    1             0
152514       0                    1             0
233330       0                    1             0
243723       0                    1             0
137288       0                    1             0
112563       0                    1             0
53439        0                    1             0
58726        0                    1             0

LinearSVC=right, Decision Tree= wrong:
         Actual  LinearSVC_Predicted  DT_Predicted
111633       0                    0             1
210439       0                    0             1
33857        0                    0             1
73307        0                    0             1
149805       0                    0             1
225880       0                    0             1
59364        0     